// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqhiqtpcydoofiqrzvnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxaGlxdHBjeWRvb2ZpcXJ6dm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDA1NzcsImV4cCI6MjA3MTg3NjU3N30.8eCmmPlrV70zwanOFxvlX36EYt8DCLi2SjjERHq4TaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});